[supabase]
url = "https://ekicnmcmnwzyqquibnyy.supabase.co"
key = "sb_publishable_aoxIrnVOuFkmtFJbndOOpg_QOEeOUy5"

[telegram]
token = "8318393313:AAHaN9NtFFw4R29DbRKGG3_HFTwfa4P7-w8"
chat_id = "-5258765663"